---
- name: Update MOTD
  hosts: all
  become: true
 
  tasks:
    - name: Set MOTD
      copy:
        content: |
          Welcome to your server!
          This is a custom MOTD set by Ansible.
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'
