---
- name: Create an empty text file
  hosts: all

  tasks:
    - name: Ensure the file exists and is empty
      file:
        path: C:\Users\m.proia\Desktop\traefik
        state: touch
        mode: '0644'
