---
- name: Create an empty text file
  hosts: all
  become: yes

  tasks:
    - name: Ensure the file exists and is empty
      file:
        path: G:\Il mio Drive\Event-Driven Ansible Demo
        state: touch
        mode: '0644'
